#!/bin/sh

set -e

source "${JBOSS_CONTAINER_UTIL_LOGGING_MODULE}/logging.sh"

if [ "${SCRIPT_DEBUG}" = "true" ] ; then
    set -x
    log_info "Script debugging is enabled, allowing bash commands and their arguments to be printed as they are executed"
fi

source "${JBOSS_CONTAINER_MAVEN_S2I_MODULE}/maven-s2i"
source "${JBOSS_CONTAINER_JDV_S2I_MODULE}/s2i-core-hooks"

maven_s2i_build

